# ---------------------------------------- #
# +--------------------------------------+ 
# |           Command Blocker!           | 
# | Blocks players from seeing commands! | 
# |            (c): TreyRuffy            | 
# +--------------------------------------+ 
# ---------------------------------------- #

# -------------------------------------------------------------------------------- #
# +------------------------------------------------------------------------------+ 
# | Add blocked commands and set permissions in:                                 |
# | disabled.yml                                                                 |
# |                                                                              |
# | Main permissions are:                                                        |
# | cb.add    -> /cb add                                                         |
# | cb.remove -> /cb remove                                                      |
# | cb.reload -> /cb reload                                                      |
# +------------------------------------------------------------------------------+
# -------------------------------------------------------------------------------- #

Default:
    # This is the default message to show.
    Message: '&cSorry, the owner has disabled that command.'
    # This is the default permission. Placeholders are %command% -> Command sent.
    ## %command% does not include any colons ##
    Permission: cb.allow.%command%
Messages:
    # This message will be sent to players without permission to do /cb
    NoPermission: '&cYou do not have the required permissions to execute this command.'