# ---------------------------------------- #
# +--------------------------------------+ 
# |           Command Blocker!           | 
# | Blocks players from seeing commands! | 
# |            (c): TreyRuffy            | 
# +--------------------------------------+ 
# ---------------------------------------- #

# -------------------------------------------------------------------------------- #
# +------------------------------------------------------------------------------+ 
# | Permissions: These are all the permissions!                                  |
# |              cb.allow.*       - Allows players to use all commands.          |
# |              cb.allow.blocked - Allows players to use the disabled commands. |
# |              cb.allow.help    - Allows players to use /help.                 |
# |              cb.allow.m.help  - Allows players to use /minecraft:help.       |
# |              cb.allow.version - Allows players to use /version.              |
# |              cb.allow.me      - Allows players to use /me.                   |
# |              cb.allow.m.me    - Allows players to use /minecraft:me.         |
# |              cb.allow.reload  - Allows players to use /reload.               |
# |              cb.allow.restart - Allows players to use /restart.              |
# |              cb.allow.stop    - Allows players to use /stop.                 |
# |              cb.allow.op      - Allows players to use /op.                   |
# |              cb.allow.deop    - Allows players to use /deop.                 |
# +------------------------------------------------------------------------------+
# -------------------------------------------------------------------------------- #

# ----------------------------------------------------------------------------------------- #
# +---------------------------------------------------------------------------------------+
# | DisabledCommands: #Allows you set your own disabled commands! :D                      |
# |   - icanhasbukkit                                                                     |
# |   - timings                                                                           |
# |   - bukkit:timings                                                                    |
# | Language: #Allows you to set the text it sends the player, if they type the command!  |
# |   YourDisabled: '&cSorry, the owner has blocked that command.' #For DisabledCommands  |
# |   Plugins: 'Plugins (0): &aNone... Sorry about that.' #For /pl and /plugin            |
# |   Help: '&cSorry, I can''t help you with this. :/' #For /help and /?                  |
# |   Version: '&6The Minecraft version you are on!' #For /version and /ver               |
# |   Me: '&7Vampires cannot see /me messages. :/' #For /me                               |
# |   Reload: '&6Were you really expecting that to work?!' #For /reload                   |
# |   Restart: '&aI do not even know what you were expecting with this...' #For /restart  |
# |   Stop: '&cWe''d rather you didn't try to stop the server. kthx' #For /stop           |
# |   Op: '&6Umm... Yeahh... No. :/' #For /op                                             |
# |   Deop: '&cWe''d rather you didn''t try to deop our staff.' #For /deop                |
# +---------------------------------------------------------------------------------------+
# ----------------------------------------------------------------------------------------- #

DisabledCommands:
    - icanhasbukkit
    - timings
    - bukkit:timings
Language:
    YourDisabled: '&cSorry, the owner has blocked that command.'
    Plugins: 'Plugins (0): &aNone... Sorry about that.'
    Help: '&cSorry, I can''t help you with this. :/'
    Version: '&6The Minecraft version you are on!'
    Me: '&7Vampires cannot see /me messages. :/'
    Reload: '&6Were you really expecting that to work?!'
    Restart: '&aI do not even know what you were expecting with this...'
    Stop: '&cWe''d rather you didn''t try to stop the server. kthx'
    Op: '&6Umm... Yeahh... No. :/'
    Deop: '&cWe''d rather you didn''t try to deop our staff.'